### ISSUE TITLE
Manual refresh?

### ISSUE THREAD

**Issue by robertmuehsig** [pydt/client#10]
I'm not sure if you poll the current game status (and if you do how often) because the client doesn't show when it was "refreshed". Sometimes I restart the client to just make sure everything is up to date - maybe a "manual refresh" button would be nice.

**Comment by mrosack** [comment]
The client gets push notifications from the server, so it should never be out of date.  Let me know if you've encountered a scenario where a turn was available and the client didn't see it.  Thanks!

**Comment by robertmuehsig** [comment]
![image](https://user-images.githubusercontent.com/756703/30425019-0aa39b8c-9948-11e7-8dab-8b900665cca8.png)

The client was running on PC A (where Civ is not installed), then I got the notification, started PC B (with Civ installed) and used the PYDT-Client to play my turn - submitted it and now it seem PC A  was stuck for a couple of minutes.

Its now back normal. On the other PC I had some troubles because the WIFI was not available and after I was online the client also needed a couple of minutes to get the latest state.

**Comment by mrosack** [comment]
That does make sense - the connection to AWS IoT could get flaky on a wifi connection.  Right now the worst case scenario is 10 minutes for an update if IoT isn't working.  Maybe I'll go back to dumb polling every minute in addition to IoT - the main issue is it's hard to tell when the IoT connection goes bad, we have a large MQTT timeout to keep costs down (see https://rosacksoftwaresolutions.com/2017/08/26/real-time-serverless-notifications-with-aws-iot/).  If I have time, I'll look into adding a footer with the last updated date and a manual refresh button.

**Comment by mrosack** [comment]
I went ahead and added a manual refresh button in 1.2.5.
