### ISSUE TITLE
Weird JavaScript error prevents me from uploading turns

### ISSUE THREAD

**Issue by deiga** [pydt/client#12]
Since 1.1.25 I've been getting the following errors each time I download a save and when it tries to locate the save for uploading 
![image](https://user-images.githubusercontent.com/27202/33244888-1131bf8e-d308-11e7-8af7-824238b819e3.png)

**Comment by mrosack** [comment]
I don't think 1.1.25 would have caused any new problems, because the only change was the URL of the API.  Did you change the location of your My Documents folder recently?

**Comment by deiga** [comment]
@mrosack Not that I know of

**Comment by deiga** [comment]
@mrosack But what about it if I had? Why wouldn't this client work any more?

**Comment by mrosack** [comment]
The client guesses your saves path from the location of your my documents folder.  Do you know where your save files are on your PC?  I haven't had any other reports of this issue, so I'm trying to figure out why you're having the problem.

**Comment by deiga** [comment]
This is my current saves path `C:\Users\darks\OneDrive\Asiakirjat\My Games\Sid Meier's Civilization VI\Saves`

`Asiakirjat == Documents`

**Comment by mrosack** [comment]
I'm assuming the OneDrive in the path means your my documents is in OneDrive?  Has it been that way for a while?  This looks like a similar bug (https://github.com/atom/fuzzy-finder/issues/324), maybe electron is having a problem with files in OneDrive?

**Comment by deiga** [comment]
I honestly don't know if they've moved there recently or a long while ago. Based on the sudden failures I'd reckon the move has happened recently.

**Comment by deiga** [comment]
Huh, it's suddenly fixed...

**Comment by mrosack** [comment]
Is it still saving to the OneDrive folder now that it's working?

**Comment by deiga** [comment]
@mrosack  Yes, it is. At least I didn't change anything :D

I did send a PR to electron which should fix these issues in the future, but until they merge it we can't really know https://github.com/electron/node/pull/27
