### ISSUE TITLE
Auto play mode && auto downloaded to cache

### ISSUE THREAD

**Issue by Valamas** [pydt/client#23]
auto download, auto upload. controlled by toggle switch on client face near refresh button. same toggle to also show on the playturn screen. the playturn screen would automatically be shown.

in addition, rather than waiting for the user to click to download, the client should have already downloaded and it should be click to play to speed things up. just move the save from the downloaded cache.

**Comment by mrosack** [comment]
I implemented a background turn downloading service in f23fe554a526fef73c4ee4a04c7585816969035e that I think takes care of most of your needs here.
