### ISSUE TITLE
Change minimize, close behaviour and tray icon behaviour

### ISSUE THREAD

**Issue by Valamas** [pydt/client#24]
I have been caught out before and my guess new users do too. Closing the client completely closes it and (for new users), they forget to play their first turns after a while. I have nudged a couple through the smack talk.

Minimize should to just that, the app remains in the task bar.
Close should close to the tray. 
Double clicking the tray should show the client.

**Comment by mrosack** [comment]
cleaned up all the window behavior per your suggestions in 180d383d863c298b570685db5f9254525a4b964c, will be in next release
