### ISSUE TITLE
Cannot cancel download

### ISSUE THREAD

**Issue by Valamas** [pydt/client#37]
A game could be downloading slowly. Sometimes I go for the "have you tried turning it off and on again" and the download happens at a speed you normally have.

The problem is there is no cancel button to cancel the download and return you to the game list. You have to actually close and reopen the client. 

I request a cancel button while the download progress bar is filling. 

(I actually wrote 3/4 of this while the client finally downloaded 1 Mb)

**Comment by mrosack** [comment]
turn uploads/downloads can now be cancelled, fixed in 531979437e25e9475cce315082f3b8dcd8bc82f8, will be in next release
