### ISSUE TITLE
Epic Games Store Support

### ISSUE THREAD

**Issue by meisterlampe** [pydt/client#38]
Hi.

Civ 6 is/was available in the epic games store for free.
So how about supporting this launcher? :)

I guess, the user needs some option for each game, which launcher he wants to use. So it is bit more work to do, than just updating some path.

Best wishes
meisterlampe

**Comment by mrosack** [comment]
Added support in 1.4.0

**Comment by ShawnAukstak** [comment]
@mrosack works great, thank you! 🙏

**Comment by meisterlampe** [comment]
Wow. Thanks for adding it that fast!
