### ISSUE TITLE
Secondary sort, games with comments

### ISSUE THREAD

**Issue by Valamas** [pydt/client#44]
I have 20 or so games going ATM. So when a game has a comment waiting for me to view, I do not see it because the games are sorted by "your-turn".

Please sort games by your-turn, then unread comments.

**Comment by Valamas** [comment]
i propose the following sort
Your turn sorted by most recent since-time (e.g. my friend is online and we are playing turns almost concurrently)
then unread comments

**Comment by mrosack** [comment]
Added behavior as you described in f8a2771d1a4518e9c27c68ac4de7317e67d9ac40, will be in next release
