### ISSUE TITLE
Repeated connection issues

### ISSUE THREAD

**Issue by Osprey2021** [pydt/client#69]
After I start client (version 2.1.5) I see my games. But when I check after a while I only see error: "There was an error loading your games. Please check your internet connection." Clicking Refresh shows the same error. Only restarting client helps but soon error reappears.

**Comment by mrosack** [comment]
Hmm, I haven't heard many complaints, and there weren't a lot of big changes in this version - if you could go to Debug/Developer Tools and take a screenshot of the Console tab when it goes bad that might be helpful.

**Comment by Osprey2021** [comment]
It seems that problem went away by itself. I don't experience it anymore for some reason.
